---

################################################
# 					Config file     		   #
################################################


############	Archiver config 	############

# File name of the archive containing all projects
src: projects.zip

# The destination directory for these projects
dest: projects


############  	Organiser config 	############

# Projects naming, useful to rename folders
projects_names: !ruby/regexp '/^[a-zA-Z]+[ ]+[a-zA-Z]+/'


############ 	Generator config '	############

# The file name for results which will be generated
out: results

# The type/format of the previous file => currently supported: [csv, html, xls]
out_format:
- csv
- html

# Ressources directory
# (needed for html format)
res_dir: res


############	Reviser config 		############

# The type of project (<type>.yml must exists)
type: Labyrinthe

# Default timeout
# shall be overriden in sorts
timeout: 5


############	Global config 		############

#
# Criterias you want for analysis
# Can be overriden or declared in
# project's config file
#
criteria:
  :all_files: Fichiers
  :src_files: Fichiers sources
  :lines_count: Nombre de lignes de code
  :comments_count: Nombre de lignes de commentaires
  :compile: Resultats compilation
  :execute: Resultats execution

extensions:
  :memleaks: Fuites memoires


# Options of all components
# For the moment, there is just verbose option (for logger)
options: 
  :verbose: true
  :log_dir: logs
