#
#   Reviser => a semi-automatic tool for student's projects evaluation
#
#   Copyright (C) 2015 Renan Strauss
#   Copyright (C) 2015 Yann Prono
#   Copyright (C) 2015 Romain Ruez
#   Copyright (C) 2015 Anthony Cerf
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

################################################
# 	           Template config file   	       #
################################################


########	Archiver config 	########

# File name of the archive containing all projects
src: projects.zip

# The destination directory for these projects
dest: projects


########	Organiser config 	########

# Conventiong naming of projects, useful to rename folders 
# You have to write a pseudo-regex with some constants:
# 	      [ GROUP, FIRSTN, NAME ]
#
# '^GROUP_NAME_NAME'		=> Project starts with GROUP (S2A for example) and contains two names.
# '^GROUP_NAME(_NAME)*'	   	=> Project starts with GROUP and contains minimum one name.
# '^TP_html_NAME_FIRSTN' 	=> name starts by 'TP_html_' and contains a name and firstname.
projects_names: '^FIRSTN NAME'


########	Generator config 	########

# The file name for results which will be generated
out: results

# The type/format of the previous file => currently supported: [csv, html, xls]
out_format:
- csv
- html

########	Reviser config		########

# The type of project (<type>.yml must exists)
type: example/Labyrinthe


########	Global config		########

# Criteria you want for analysis
# Can be overriden or declared in
# project's config file
#
# Basics criteria, available in lib/helpers
criteria:
  - all_files
  - src_files
  - lines_count
  - comments_count
  - compile
  - execute

# Extensions you want to use
# Some are already available in ext/
# but you can also define your own
# and add your criteria here
# (don't forget to register it with Reviser::register)
# extensions:
# - my_custom_criterion
#

# Whether to create a git repository for each project
# relies on 'git' gem
# create_git_repo: true

# Options of all components
# For the moment, there is just verbose option (for logger)
options:
  :log_dir: logs
  # mode of logger	=> [org, txt ...]
  :log_mode: org