---

################################################
# 					Config file     		   #
################################################


############	Archiver config 	############

# File name of the archive containing all projects
src: projects.zip

# The destination directory for these projects
dest: projects


############  	Organiser config 	############

# Projects naming, useful to rename folders
# NAME => ONLY the name of the student
# NAME#FIRST => the name and the firstime  of the student, separated with a space
# 'S3A_NAME_NAME'   'S3A_NAME#FIRST'   
projects_names: 'NAME#FIRST'


############ 	Generator config '	############

# The file name for results which will be generated
out: results

# The type/format of the previous file => currently supported: [csv, html, xls]
out_format:
- csv
- html

# Ressources directory
# (needed for html format)
res_dir: res


############	Reviser config 		############

# The type of project (<type>.yml must exists)
type: Labyrinthe

# Default timeout
# shall be overriden in sorts
timeout: 5


############	Global config 		############

#
# Criterias you want for analysis
# Can be overriden or declared in
# project's config file
#
criteria:
  - all_files
  - src_files
  - lines_count
  - comments_count
  - compile
  - execute

extensions:
  - memleaks


# Options of all components
# For the moment, there is just verbose option (for logger)
options: 
  :verbose: true
  :log_dir: logs
